### ISSUE TITLE
Toxic detected as arcane buffer and berserker

### ISSUE THREAD

**Issue by Istaryu** [tmikoss/archnemesis-detector#10]
![image](https://user-images.githubusercontent.com/67639805/153540873-8efaeb06-13f7-47c6-ae5b-a2b8e27cba6b.png)

**Comment by tmikoss** [comment]
Additional information required, please click on the mis-identified icon and follow the steps outlined there.

**Comment by tmikoss** [comment]
Additional information required, please click on the mis-identified icon in the right-side grid and follow the steps outlined there.

**Comment by Istaryu** [comment]
{
  "x": 1,
  "y": 0,
  "empty": false,
  "id": "arcane-buffer",
  "matchedPct": 59.25925925925926,
  "topMatches": [
    {
      "id": "echoist",
      "match": 62.48285322359396
    },
    {
      "id": "arcane-buffer",
      "match": 59.25925925925926
    },
    {
      "id": "berserker",
      "match": 58.91632373113855
    },
    {
      "id": "toxic",
      "match": 58.882030178326474
    },
    {
      "id": "incendiary",
      "match": 56.927297668038406
    },
    {
      "id": "hasted",
      "match": 53.566529492455416
    },
    {
      "id": "deadeye",
      "match": 53.32647462277092
    },
    {
      "id": "dynamo",
      "match": 53.25788751714678
    },
    {
      "id": "sentinel",
      "match": 53.155006858710564
    },
    {
      "id": "chaosweaver",
      "match": 53.12071330589849
    }
  ]
}

**Comment by Istaryu** [comment]
{
  "x": 3,
  "y": 1,
  "empty": false,
  "id": "berserker",
  "matchedPct": 64.81481481481481,
  "topMatches": [
    {
      "id": "berserker",
      "match": 64.81481481481481
    },
    {
      "id": "echoist",
      "match": 63.58024691358025
    },
    {
      "id": "arcane-buffer",
      "match": 61.86556927297668
    },
    {
      "id": "toxic",
      "match": 61.69410150891632
    },
    {
      "id": "incendiary",
      "match": 59.60219478737997
    },
    {
      "id": "hasted",
      "match": 56.927297668038406
    },
    {
      "id": "deadeye",
      "match": 55.31550068587106
    },
    {
      "id": "dynamo",
      "match": 54.83539094650205
    },
    {
      "id": "chaosweaver",
      "match": 54.801097393689986
    },
    {
      "id": "sentinel",
      "match": 54.56104252400549
    }
  ]
}
