### ISSUE TITLE
Arcane buffer detected as echoist

### ISSUE THREAD

**Issue by Istaryu** [tmikoss/archnemesis-detector#11]
![image](https://user-images.githubusercontent.com/67639805/153540969-3ee9ee1a-4444-4e38-84d7-653d4f5f310b.png)

**Comment by tmikoss** [comment]
Additional information required, please click on the mis-identified icon in the right-side grid and follow the steps outlined there.

**Comment by Istaryu** [comment]
{
  "x": 6,
  "y": 1,
  "empty": false,
  "id": "echoist",
  "matchedPct": 60.15089163237312,
  "topMatches": [
    {
      "id": "echoist",
      "match": 60.15089163237312
    },
    {
      "id": "berserker",
      "match": 59.36213991769547
    },
    {
      "id": "arcane-buffer",
      "match": 58.91632373113855
    },
    {
      "id": "toxic",
      "match": 55.89849108367627
    },
    {
      "id": "incendiary",
      "match": 55.24691358024691
    },
    {
      "id": "hasted",
      "match": 53.01783264746228
    },
    {
      "id": "dynamo",
      "match": 52.22908093278464
    },
    {
      "id": "chaosweaver",
      "match": 51.989026063100134
    },
    {
      "id": "deadeye",
      "match": 51.95473251028807
    },
    {
      "id": "sentinel",
      "match": 51.78326474622771
    }
  ]
}
