### ISSUE TITLE
Crystal-skinned detected as echoist

### ISSUE THREAD

**Issue by Istaryu** [tmikoss/archnemesis-detector#12]
![image](https://user-images.githubusercontent.com/67639805/153541059-a96bfdfc-592a-47ab-9fe4-cd6707815435.png)

**Comment by tmikoss** [comment]
Additional information required, please click on the mis-identified icon in the right-side grid and follow the steps outlined there.

**Comment by Istaryu** [comment]
{
  "x": 6,
  "y": 2,
  "empty": false,
  "id": "mana-siphoner",
  "matchedPct": 42.62688614540466,
  "topMatches": [
    {
      "id": "mana-siphoner",
      "match": 42.62688614540466
    },
    {
      "id": "crystal-skinned",
      "match": 42.249657064471876
    },
    {
      "id": "temporal-bubble",
      "match": 39.84910836762688
    },
    {
      "id": "hexer",
      "match": 39.40329218106996
    },
    {
      "id": "assassin",
      "match": 38.40877914951989
    },
    {
      "id": "executioner",
      "match": 37.928669410150896
    },
    {
      "id": "heralding-minions",
      "match": 37.757201646090536
    },
    {
      "id": "trickster",
      "match": 37.58573388203018
    },
    {
      "id": "effigy",
      "match": 37.517146776406044
    },
    {
      "id": "drought-bringer",
      "match": 37.44855967078189
    }
  ]
}
