### ISSUE TITLE
Arcane buffer detected as berserker

### ISSUE THREAD

**Issue by Istaryu** [tmikoss/archnemesis-detector#14]
![image](https://user-images.githubusercontent.com/67639805/153541198-30098630-cdb7-495d-8d3a-c43ba3fbf492.png)

I have an 1080p monitor but run the game in 1600x900 resolution, if that matters anything.

**Comment by tmikoss** [comment]
Additional information required, please click on the mis-identified icon in the right-side grid and follow the steps outlined there.

**Comment by Istaryu** [comment]
{
  "x": 5,
  "y": 3,
  "empty": false,
  "id": "berserker",
  "matchedPct": 65.6721536351166,
  "topMatches": [
    {
      "id": "berserker",
      "match": 65.6721536351166
    },
    {
      "id": "arcane-buffer",
      "match": 64.16323731138546
    },
    {
      "id": "echoist",
      "match": 62.414266117969824
    },
    {
      "id": "toxic",
      "match": 61.24828532235939
    },
    {
      "id": "incendiary",
      "match": 59.465020576131685
    },
    {
      "id": "hasted",
      "match": 57.61316872427983
    },
    {
      "id": "dynamo",
      "match": 55.349794238683124
    },
    {
      "id": "chaosweaver",
      "match": 55.17832647462277
    },
    {
      "id": "deadeye",
      "match": 54.83539094650205
    },
    {
      "id": "sentinel",
      "match": 54.76680384087791
    }
  ]
}
