### ISSUE TITLE
Suggestion: Sort Mods and Recipes Alphabetically

### ISSUE THREAD

**Issue by ForgottenHero** [tmikoss/archnemesis-detector#2]
I love this tool, it works flawlessly so far.

Could you possibly make the page sort all mods and recipes alphabetically? That'd make it a lot easier to scan through quickly to find what I'm looking for.

**Comment by tmikoss** [comment]
@ForgottenHero there's a new versiomn released where detected mods are sorted, in the list view. Recipes UI is due for an overhaul later on.
