### ISSUE TITLE
Custom game resolution

### ISSUE THREAD

**Issue by SnosMe** [tmikoss/archnemesis-detector#3]
Looks like you have hard-coded coordinates for 16:9? Anyway, it didn't  find the correct position and as a result a waterfall of incorrect recognitions.

![image](https://user-images.githubusercontent.com/4292308/153457840-2581373d-581e-4a72-85f2-1c4061f3542c.png)

**Comment by tmikoss** [comment]
@SnosMe what resolution are you running? Windowed / fullscreen?

**Comment by SnosMe** [comment]
This should not matter, UI scaling in poe is based on window height.

**Comment by tmikoss** [comment]
@SnosMe And so is the placement code, see https://github.com/tmikoss/archnemesis-detector/issues/1 . There must be something else going on. So, what resolution are you running? Windowed / fullscreen? Screenshot sample would help.

**Comment by SnosMe** [comment]
![image](https://user-images.githubusercontent.com/4292308/153558734-f50e2b08-538e-477b-be3d-341a5f216104.png)

![image](https://user-images.githubusercontent.com/4292308/153558763-eaff4200-8a2f-457e-9a68-4b2879f53bd6.png)

**Comment by SnosMe** [comment]
Oh, I'm sorry, I forgot that Alt+PrntScreen captures window titlebar too.
Basically, I need to press F8 to get the correct screenshot made by the game.
So my feature request then would be if possible detect titlebar (including light/dark Windows theme), because going to a folder with screenshots is annoying. It's probably lowprio and hard, so I'll close it.
