### ISSUE TITLE
Problem with Samples and Suggestions

### ISSUE THREAD

**Issue by danmarzola** [tmikoss/archnemesis-detector#4]
As GGG put L:XX inside the the icon, many times feature will fail to detect, maybe you need to get the superior part only so it will match better or cause other problems

For the pos processing website, one single column for both detected and results will cause rollbar, my suggestion is to limit to 7 itens and start a new column.

Your work is amazing anyway, i was tempt to do it with AHK and [Find Text](https://autohotkey.com/boards/viewtopic.php?f=6&t=17834), but the sample would be a nightmare

**Comment by tmikoss** [comment]
Thank you for the suggestions, will take them in account moving forward.
