### ISSUE TITLE
Heralding minions is recognized as temporal bubble

### ISSUE THREAD

**Issue by Istaryu** [tmikoss/archnemesis-detector#7]
![image](https://user-images.githubusercontent.com/67639805/153540617-2ee1346d-2c90-4f49-ab05-b62d0ad47a91.png)

**Comment by tmikoss** [comment]
Additional information required, please click on the mis-identified icon in the right-side grid and follow the steps outlined there.

**Comment by Istaryu** [comment]
{
  "x": 7,
  "y": 0,
  "empty": false,
  "id": "temporal-bubble",
  "matchedPct": 45.370370370370374,
  "topMatches": [
    {
      "id": "temporal-bubble",
      "match": 45.370370370370374
    },
    {
      "id": "heralding-minions",
      "match": 41.666666666666664
    },
    {
      "id": "mirror-image",
      "match": 40.054869684499316
    },
    {
      "id": "assassin",
      "match": 39.09465020576132
    },
    {
      "id": "frost-strider",
      "match": 38.888888888888886
    },
    {
      "id": "mana-siphoner",
      "match": 38.888888888888886
    },
    {
      "id": "flame-strider",
      "match": 38.203017832647454
    },
    {
      "id": "trickster",
      "match": 37.68861454046639
    },
    {
      "id": "soul-eater",
      "match": 37.68861454046639
    },
    {
      "id": "evocationist",
      "match": 37.41426611796982
    }
  ]
}
