### ISSUE TITLE
Empowered elements is recognized as temporal bubble

### ISSUE THREAD

**Issue by Istaryu** [tmikoss/archnemesis-detector#9]
![image](https://user-images.githubusercontent.com/67639805/153540708-2374eaf7-9d9c-4d03-9313-c82944192fa3.png)

**Comment by tmikoss** [comment]
Additional information required, please click on the mis-identified icon in the right-side grid and follow the steps outlined there.

**Comment by Istaryu** [comment]
{
  "x": 4,
  "y": 0,
  "empty": false,
  "id": "temporal-bubble",
  "matchedPct": 49.89711934156379,
  "topMatches": [
    {
      "id": "temporal-bubble",
      "match": 49.89711934156379
    },
    {
      "id": "empowered-elements",
      "match": 49.451303155006855
    },
    {
      "id": "necromancer",
      "match": 47.94238683127572
    },
    {
      "id": "mirror-image",
      "match": 47.70233196159121
    },
    {
      "id": "soul-eater",
      "match": 47.565157750342934
    },
    {
      "id": "trickster",
      "match": 47.427983539094654
    },
    {
      "id": "evocationist",
      "match": 46.982167352537715
    },
    {
      "id": "assassin",
      "match": 46.87928669410151
    },
    {
      "id": "executioner",
      "match": 46.0562414266118
    },
    {
      "id": "mana-siphoner",
      "match": 45.8161865569273
    }
  ]
}
